#ifndef Enum_h__
#define Enum_h__

enum RESOURCEID { RESOURCE_STATIC, RESOURCE_LOGO, RESOURCE_STAGE, RESOURCE_END };
enum LOADINGID  { LOADING_LOGO, LOADING_STAGE, LOADING_BOSS, LOADING_END };
enum SCENEID	{ SCENE_INTRO, SCENE_LOGO, SCENE_STAGE };
enum LAYERID	{ LAYER_GAMEOBJECT };

enum PLAYER_STATE
{
	PLAYER_IDLE, PLAYER_WALK, PLAYER_RUN, PLAYER_JUMP, PLAYER_DOWN,
	PLAYER_IDLE_TURN_L180, PLAYER_IDLE_TURN_L90, PLAYER_IDLE_TURN_R90, PLAYER_IDLE_TURN_R180,
	PLAYER_DOOR_IN, PLAYER_DOOR_LOOP, PLAYER_DOOR_OUT, PLAYER_DOOR_OPEN,
	PLAYER_TRUNK_IN, PLAYER_TRUNK_OUT, 
	PLAYER_CUPBOARD_IN, PLAYER_CUPBOARD_OUT, 
	PLAYER_TORCH_ON, 
	PLAYER_LEVER_ON,
	PLAYER_TRUNK_CATCH, PLAYER_CUPBOARD_CATCH, PLAYER_CATCH_HURT,
	PLAYER_ROLL, PLAYER_SIT, 
	PLAYER_DROPIN, PLAYER_DROPOUT,
	PLAYER_FIGHT_IDLE, PLAYER_FIGHT_LEFT, PLAYER_FIGHT_RIGHT, PLAYER_FIGHT_FORWARD, PLAYER_FIGHT_BACKWARD, 
	PLAYER_FIGHT_COUNTER, PLAYER_FIGHT_HURT,
	PLAYER_FIND, PLAYER_CHEER, PLAYER_SLEEP,
	PLAYER_CARRY_PICK, PLAYER_CARRY_IDLE, PLAYER_CARRY_WALK, PLAYER_CARRY_RUN, PLAYER_CARRY_DROP,
	PLAYER_ELITE_HIDE_TRUNK, PLAYER_ELITE_HIDE_CUPBOARD,
	PLAYER_ASSASS_IN, PLAYER_ASSASS_LOOP, PLAYER_ASSASS_OUT,
	PLAYER_SHAKE_POISON,
	PLAYER_THROW_CUTLASS,
	PLAYER_DRINK_POSITION,
	PLAYER_DRINK_AFTER,
	PLAYER_MAKE_SOUND,
	PLAYER_SICK_LOOP, PLAYER_SICK_OUT,
	PLAYER_TRANSLUCENT,
	PLAYER_SWORD_ACTIVEIN, PLAYER_SWORD_ACTIVEOUT, PLAYER_ATTACK_UP,
	PLAYER_DEAD_IN,
	PLAYER_DEAD,
	PLAYER_STATE_END
};

enum ELITE_STATE
{
	/*  Basic  */
	ELITE_IDLE, ELITE_WALK, ELITE_RUN,
	ELITE_IDLE_TURN_L180, ELITE_IDLE_TURN_L90, ELITE_IDLE_TURN_R90, ELITE_IDLE_TURN_R180,
	ELITE_RUSH, ELITE_ASSASS_IN, ELITE_ASSASS_LOOP, ELITE_ASSASS_OUT, 
	ELITE_SICK_LOOP, ELITE_SICK_OUT,
	ELITE_CUTLASS_DEAD, ELITE_DEAD,
	/*  Sword Not Active  */
	ELITE_SLEEP_IN, ELITE_SLEEP_LOOP, ELITE_SLEEP_OUT,
	ELITE_CLEAN_BROOM, ELITE_CLEAN_BROOM_OUT, ELITE_CLEAN_FLOOR, ELITE_CLEAN_WALL, ELITE_CLEAN_TABLE,
	ELITE_JOKE,
	ELITE_DRINK_IN, ELITE_DRINK_LOOP, ELITE_DRINK_OUT, ELITE_DRINK_DEAD,
	/*  Sword Active  */
	ELITE_SWORD_ACTIVEIN, ELITE_SWORD_ACTIVEOUT,
	ELITE_ATTACK_UP, ELITE_ATTACK_RIGHT, ELITE_ATTACK_LEFT, ELITE_ATTACK_COUNTER,
	ELITE_TRUNK_IN, ELITE_TRUNK_CATCH,
	ELITE_CUPBOARD_IN, ELITE_CUPBOARD_OUT, ELITE_CUPBOARD_CATCH,
	ELITE_CATCH_ATTACK,
	ELITE_HIDE_TRUNK_IN, ELITE_HIDE_CUPBOARD_IN, ELITE_HIDE,
	ELITE_CARRY_PICK, ELITE_CARRY_IDLE, ELITE_CARRY_WALK, ELITE_CARRY_RUN, ELITE_CARRY_DROP,
	ELITE_LEVER_ON,
	ELITE_STATE_END
};

enum SERVANT_STATE
{
	SERVANT_IDLE,
	SERVANT_CLEANING_LOOP, SERVANT_CLEANING_OUT,
	SERVANT_SCARY_IN, SERVANT_SCARY_LOOP, SERVANT_SCARY_OUT,
	SERVANT_THANK_IN, SERVANT_THANK_OUT,
	SERVANT_REQUEST_IN, SERVANT_REQUEST_LOOP,
	SERVANT_LTURN, SERVANT_RTURN, SERVANT_VIEW,
	SERVANT_CRAZY,
	SERVANT_STATE_END
};

enum BUTTON_UI
{
	BUTTON_E, BUTTON_F, BUTTON_C, BUTTON_MOUSE, BUTTON_LS, BUTTON_UI_END
};

enum CAMERA_PURPOSE
{
	PURPOSE_BEHAVIOR, PURPOSE_QUEST, PURPOSE_DOOR, PURPOSE_TRUNK, PURPOSE_CUPBOARD, PURPOSE_GRID, PURPOSE_FIRST_PERSON, PURPOSE_END
};

enum DIR
{
	DIR_LEFT, DIR_RIGHT, DIR_FRONT, DIR_BACK, DIR_END
};

#endif // Enum_h__
