#ifndef Enum_h__
#define Enum_h__

enum RESOURCEID { RESOURCE_STATIC, RESOURCE_LOGO, RESOURCE_STAGE, RESOURCE_END };
enum LOADINGID  { LOADING_LOGO, LOADING_STAGE, LOADING_BOSS, LOADING_END };
enum SCENEID	{ SCENE_INTRO, SCENE_LOGO, SCENE_STAGE };
enum LAYERID	{ LAYER_GAMEOBJECT };

/*  Tool  */
enum POINT_CHECK { POINT_A, POINT_B, POINT_C, POINT_END };


#endif // Enum_h__
